In [2]:
#_*_ encoding=utf-8 _*_

'''
关注股票
国金证券
万向钱潮
科大讯飞002230
'''

import tushare as ts
import numpy as np
data1 = ts.get_h_data('002230')
print data1.head(100)
''''
ktype
默认为D日线数据
D=日k线 W=周 M=月
5=5分钟 15=15分钟
30=30分钟 60=60分钟
'''

[Getting data:]####             open   high  close    low       volume        amount
date
2017-07-07  42.31  43.50  43.15  42.06  101875550.0  4.372577e+09
2017-07-06  43.03  44.95  42.55  42.44  125099891.0  5.434223e+09
2017-07-05  43.27  43.98  43.63  42.09   97501931.0  4.184952e+09
2017-07-04  43.00  43.85  43.65  42.70   93626651.0  4.051741e+09
2017-07-03  40.30  43.45  43.45  39.91  114094958.0  4.749424e+09
2017-06-30  39.78  41.44  39.90  39.58   79347654.0  3.202400e+09
2017-06-29  37.40  41.58  40.05  37.21  120193509.0  4.792900e+09
2017-06-28  36.77  38.45  37.80  36.08   92278470.0  3.424408e+09
2017-06-27  36.30  36.49  36.14  35.71   42922349.0  1.548432e+09
2017-06-26  33.90  36.39  36.39  33.90   80080011.0  2.841360e+09
2017-06-23  33.05  33.74  33.63  32.75   37421718.0  1.243574e+09
2017-06-22  32.38  34.90  33.18  32.25   61117659.0  2.055665e+09
2017-06-21  32.26  32.50  32.28  31.71   20505334.0  6.582612e+08
2017-06-20  32.30  32.38  31.95  31.89   17902232.0  5.750884e+08
2017-06-19  31.81  32.35  32.17  31.72   19889889.0  6.382446e+08
2017-06-16  32.07  32.24  31.75  31.66   15830441.0  5.045154e+08
2017-06-15  31.08  32.30  32.07  31.02   32742719.0  1.043083e+09
2017-06-14  30.99  31.25  31.08  30.67   11948633.0  3.696116e+08
2017-06-13  30.50  31.10  30.99  30.42   12184435.0  3.766217e+08
2017-06-12  31.20  31.29  30.58  30.50   15222473.0  4.700969e+08
2017-06-09  31.00  31.61  31.35  30.67   21548783.0  6.714975e+08
2017-06-08  31.32  31.39  30.98  30.90   17508391.0  5.451974e+08
2017-06-07  30.90  31.32  31.30  30.72   26190225.0  8.137368e+08
2017-06-06  30.21  30.94  30.85  30.21   20014404.0  6.136818e+08
2017-06-05  30.23  30.76  30.20  30.08   16106256.0  4.896016e+08
2017-06-02  29.52  30.24  30.14  28.62   17688846.0  5.214560e+08
2017-06-01  29.79  30.47  29.79  29.60   19707568.0  5.925180e+08
2017-05-31  30.36  30.87  29.82  29.80   20599239.0  6.262918e+08
2017-05-26  29.84  30.33  29.91  29.61   20992662.0  6.294825e+08
2017-05-25  28.85  30.00  29.84  28.62   23831103.0  7.012161e+08
...           ...    ...    ...    ...          ...           ...
2017-03-24  35.26  36.58  36.16  35.26   52842323.0  1.910335e+09
2017-03-23  35.64  36.18  35.48  34.74   47505916.0  1.688663e+09
2017-03-22  34.59  36.13  35.81  34.39   66535807.0  2.352655e+09
2017-03-21  33.51  35.73  34.93  33.29   71727984.0  2.503851e+09
2017-03-20  33.50  33.89  33.37  32.95   28923293.0  9.694758e+08
2017-03-17  34.80  34.94  33.50  33.47   39616618.0  1.361921e+09
2017-03-16  33.81  34.44  34.39  33.65   37055946.0  1.265238e+09
2017-03-15  34.07  34.14  33.64  33.39   39625389.0  1.340872e+09
2017-03-14  34.29  35.47  34.29  33.90   55464573.0  1.925068e+09
2017-03-13  34.87  35.85  34.48  34.23   63329446.0  2.222600e+09
2017-03-10  33.59  34.49  34.11  33.20   44220941.0  1.501834e+09
2017-03-09  33.70  35.01  33.49  33.49   66336306.0  2.277120e+09
2017-03-08  33.69  34.12  33.58  33.22   60864987.0  2.048670e+09
2017-03-07  31.84  35.00  34.26  31.55  119984296.0  4.049745e+09
2017-03-06  31.40  32.39  31.82  30.93   52310214.0  1.659238e+09
2017-03-03  30.26  30.88  30.71  30.01   20457403.0  6.260651e+08
2017-03-02  30.62  31.10  30.23  30.22   16886139.0  5.189586e+08
2017-03-01  30.66  30.87  30.48  30.40   12834629.0  3.937494e+08
2017-02-28  30.90  31.17  30.66  30.30   20871484.0  6.414223e+08
2017-02-27  30.58  31.46  31.04  30.46   35032547.0  1.094280e+09
2017-02-24  30.65  31.20  30.66  30.51   26192671.0  8.106248e+08
2017-02-23  30.68  30.68  30.22  30.14   16808007.0  5.109187e+08
2017-02-22  30.41  30.94  30.69  30.20   32672164.0  1.003042e+09
2017-02-21  29.48  30.74  30.49  29.30   40007974.0  1.216169e+09
2017-02-20  29.20  29.68  29.40  29.12   10296017.0  3.035876e+08
2017-02-17  29.72  29.81  29.10  29.10   13670993.0  4.037076e+08
2017-02-16  29.25  30.07  29.85  29.04   22174101.0  6.571643e+08
2017-02-15  29.38  29.54  29.18  29.06   13483246.0  3.960384e+08
2017-02-14  29.25  29.73  29.32  29.20   14706985.0  4.344114e+08
2017-02-13  29.22  29.58  29.19  29.07   15169946.0  4.458001e+08

[100 rows x 6 columns]
           date    open   close    high     low     volume    code
359  2015-06-05  51.448  53.435  59.344  51.121  2762322.0  002230
360  2015-06-12  52.640  51.339  54.180  49.889  2157904.0  002230
361  2015-06-19  51.945  40.185  52.958  40.136  2099121.0  002230
362  2015-06-26  40.324  35.050  42.410  35.050  1477409.0  002230
363  2015-07-03  35.557  36.808  38.735  28.386  4013194.0  002230
364  2015-07-07  40.493  32.895  40.493  32.895  1729311.0  002230
365  2015-07-17  36.183  38.924  40.722  32.577  2204274.0  002230
366  2015-07-24  39.232  41.169  43.920  38.497  3111520.0  002230
367  2015-07-31  39.729  37.017  41.119  33.372  2477697.0  002230
368  2015-08-07  36.252  38.020  39.242  33.849  1799206.0  002230
369  2015-08-14  38.298  39.341  41.000  37.633  1972153.0  002230
370  2015-08-21  39.500  34.574  40.821  33.769  2282124.0  002230
371  2015-08-28  32.776  28.396  33.253  23.221  2215216.0  002230
372  2015-09-02  28.307  25.814  28.307  23.867  1186767.0  002230
373  2015-09-11  26.568  29.379  30.790  26.032  1549281.0  002230
374  2015-09-18  29.747  26.519  29.767  23.797  1392815.0  002230
375  2015-09-25  25.923  26.429  29.101  25.853  1253318.0  002230
376  2015-09-30  26.797  26.618  27.879  26.171   544583.0  002230
377  2015-10-09  27.909  30.392  30.740  27.512   706413.0  002230
378  2015-10-16  30.700  33.312  33.998  30.412  1778771.0  002230
379  2015-10-23  33.461  39.063  40.056  32.478  3475259.0  002230
380  2015-10-30  39.232  37.097  41.516  36.054  2579885.0  002230
381  2015-11-06  35.756  38.686  38.974  34.762  2055950.0  002230
382  2015-11-13  38.715  36.878  41.417  36.818  2336974.0  002230
383  2015-11-20  36.252  38.805  40.007  35.756  2448666.0  002230
384  2015-11-27  37.573  34.951  38.934  33.789  1929124.0  002230
385  2015-12-04  34.762  35.199  36.004  32.677  1066603.0  002230
386  2015-12-11  35.309  34.514  36.203  33.769   877469.0  002230
387  2015-12-18  34.206  38.239  39.232  34.018  1617680.0  002230
388  2015-12-25  38.437  37.265  38.686  36.898  1494981.0  002230
..          ...     ...     ...     ...     ...        ...     ...
429  2016-12-16  28.369  27.771  28.369  27.103   552972.0  002230
430  2016-12-23  27.711  26.864  27.711  26.824   318828.0  002230
431  2016-12-30  26.814  27.003  27.153  26.136   296197.0  002230
432  2017-01-06  27.203  27.701  28.738  27.113   448618.0  002230
433  2017-01-13  27.731  27.013  28.309  26.944   369993.0  002230
434  2017-01-20  26.894  26.664  26.894  25.219   361838.0  002230
435  2017-01-26  26.664  26.944  27.123  26.575   167133.0  002230
436  2017-02-03  27.123  27.970  28.190  26.973   171858.0  002230
437  2017-02-10  27.990  29.356  30.402  27.691  1376199.0  002230
438  2017-02-17  29.226  29.107  30.074  29.037   792050.0  002230
439  2017-02-24  29.206  30.662  31.200  29.127  1259766.0  002230
440  2017-03-03  30.582  30.711  31.459  30.014  1060820.0  002230
441  2017-03-10  31.399  34.111  35.008  30.931  3437165.0  002230
442  2017-03-17  34.868  33.502  35.855  33.393  2350917.0  002230
443  2017-03-24  33.502  36.164  36.583  32.954  2675351.0  002230
444  2017-03-31  36.064  34.988  36.662  34.390  1587277.0  002230
445  2017-04-07  34.788  35.058  36.084  34.739   927388.0  002230
446  2017-04-14  35.018  32.466  35.018  32.117  1460835.0  002230
447  2017-04-21  32.356  30.570  32.894  30.103  1190803.0  002230
448  2017-04-28  30.750  31.700  32.390  29.810  1028358.0  002230
449  2017-05-05  31.630  30.470  32.090  30.330   627730.0  002230
450  2017-05-12  30.380  28.300  30.990  27.050  1270837.0  002230
451  2017-05-19  28.710  29.350  30.270  28.700  1035424.0  002230
452  2017-05-26  29.330  29.910  30.330  27.880   954932.0  002230
453  2017-06-02  30.360  30.140  30.870  28.620   579955.0  002230
454  2017-06-09  30.230  31.350  31.610  30.080  1013678.0  002230
455  2017-06-16  31.200  31.750  32.300  30.420   879285.0  002230
456  2017-06-23  31.810  33.630  34.900  31.710  1568366.0  002230
457  2017-06-30  33.900  39.900  41.580  33.900  4148218.0  002230
458  2017-07-07  40.300  43.150  44.950  39.910  5321987.0  002230

[100 rows x 7 columns]

In [4]:
data2 = ts.get_k_data('002230', ktype='D',autype='qfq')
print data2.tail(10)

           date   open  close   high    low     volume    code
630  2017-06-26  33.90  36.39  36.39  33.90   800800.0  002230
631  2017-06-27  36.30  36.14  36.49  35.71   429223.0  002230
632  2017-06-28  36.77  37.80  38.45  36.08   922784.0  002230
633  2017-06-29  37.40  40.05  41.58  37.21  1201935.0  002230
634  2017-06-30  39.78  39.90  41.44  39.58   793476.0  002230
635  2017-07-03  40.30  43.45  43.45  39.91  1140949.0  002230
636  2017-07-04  43.00  43.65  43.85  42.70   936266.0  002230
637  2017-07-05  43.27  43.63  43.98  42.09   975019.0  002230
638  2017-07-06  43.03  42.55  44.95  42.44  1250998.0  002230
639  2017-07-07  42.31  43.15  43.50  42.06  1018755.0  002230

In [5]:
# ma5：5日均价
# ma10：10日均价
# ma20:20日均价
# v_ma5:5日均量
# v_ma10:10日均量
# v_ma20:20日均量
data2.describe()

             open       close        high         low        volume
count  640.000000  640.000000  640.000000  640.000000  6.400000e+02
mean    30.446253   30.474220   31.223269   29.761123  2.937990e+05
std      7.894496    7.885341    8.224173    7.550565  1.977000e+05
min     17.178000   17.118000   17.469000   17.046000  3.335300e+04
25%     26.796250   26.725000   27.427250   26.134750  1.513525e+05
50%     29.809000   29.854000   30.298000   29.472500  2.426630e+05
75%     34.227000   34.487750   35.292000   33.240500  3.899475e+05
max     58.600000   58.004000   59.563000   55.391000  1.250998e+06

In [ ]:
data_format={
    'open':[],
    'close':[],
    'high':[],
    'low':[],
    'volume':[]
    
    
}